package phamnguyen.com.vn.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TbTinhTrangThietBi generated by hbm2java
 */
@Entity
@Table(name = "tb_tinh_trang_thiet_bi", catalog = "thietbi")
public class TbTinhTrangThietBi{

	private int maTinhTrang;
	private String tinhTrang;
	private String ghiChu;
	private Set<TbLichSuBaoTri> tbLichSuBaoTris = new HashSet<TbLichSuBaoTri>(0);

	public TbTinhTrangThietBi() {
	}

	public TbTinhTrangThietBi(String tinhTrang, String ghiChu, Set<TbLichSuBaoTri> tbLichSuBaoTris) {
		this.tinhTrang = tinhTrang;
		this.ghiChu = ghiChu;
		this.tbLichSuBaoTris = tbLichSuBaoTris;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_tinh_trang", unique = true, nullable = false)
	public int getMaTinhTrang() {
		return this.maTinhTrang;
	}

	public void setMaTinhTrang(int maTinhTrang) {
		this.maTinhTrang = maTinhTrang;
	}

	@Column(name = "tinh_trang", length = 20)
	public String getTinhTrang() {
		return this.tinhTrang;
	}

	public void setTinhTrang(String tinhTrang) {
		this.tinhTrang = tinhTrang;
	}

	@Column(name = "ghi_chu", length = 200)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tbTinhTrangThietBi")
	@Fetch(FetchMode.SELECT)
	public Set<TbLichSuBaoTri> getTbLichSuBaoTris() {
		return this.tbLichSuBaoTris;
	}

	public void setTbLichSuBaoTris(Set<TbLichSuBaoTri> tbLichSuBaoTris) {
		this.tbLichSuBaoTris = tbLichSuBaoTris;
	}

}
