package phamnguyen.com.vn.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbXuat generated by hbm2java
 */
@Entity
@Table(name = "tb_xuat", catalog = "thietbi")
public class TbXuat{
	private int maXuat;
	private TbChiTietNhapXuat tbChiTietNhapXuat;
	private TbPhieuXuat tbPhieuXuat;
	private int soLuongXuat;
	private String tinhTrangThietBi;
	private Set<TbLichSuBaoTri> tbLichSuBaoTris = new HashSet<TbLichSuBaoTri>(0);

	public TbXuat() {
	}

	public TbXuat(TbChiTietNhapXuat tbChiTietNhapXuat, TbPhieuXuat tbPhieuXuat, int soLuongXuat,
			String tinhTrangThietBi, Set<TbLichSuBaoTri> tbLichSuBaoTris) {
		this.tbChiTietNhapXuat = tbChiTietNhapXuat;
		this.tbPhieuXuat = tbPhieuXuat;
		this.soLuongXuat = soLuongXuat;
		this.tinhTrangThietBi = tinhTrangThietBi;
		this.tbLichSuBaoTris = tbLichSuBaoTris;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_xuat", unique = true, nullable = false)
	public int getMaXuat() {
		return this.maXuat;
	}

	public void setMaXuat(int maXuat) {
		this.maXuat = maXuat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "thiet_bi_id")
	public TbChiTietNhapXuat getTbChiTietNhapXuat() {
		return this.tbChiTietNhapXuat;
	}

	public void setTbChiTietNhapXuat(TbChiTietNhapXuat tbChiTietNhapXuat) {
		this.tbChiTietNhapXuat = tbChiTietNhapXuat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ma_phieu_xuat")
	public TbPhieuXuat getTbPhieuXuat() {
		return this.tbPhieuXuat;
	}

	public void setTbPhieuXuat(TbPhieuXuat tbPhieuXuat) {
		this.tbPhieuXuat = tbPhieuXuat;
	}

	@Column(name = "so_luong_xuat")
	public int getSoLuongXuat() {
		return this.soLuongXuat;
	}

	public void setSoLuongXuat(int soLuongXuat) {
		this.soLuongXuat = soLuongXuat;
	}

	@Column(name = "tinh_trang_thiet_bi", length = 20)
	public String getTinhTrangThietBi() {
		return this.tinhTrangThietBi;
	}

	public void setTinhTrangThietBi(String tinhTrangThietBi) {
		this.tinhTrangThietBi = tinhTrangThietBi;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tbXuat")
	public Set<TbLichSuBaoTri> getTbLichSuBaoTris() {
		return this.tbLichSuBaoTris;
	}

	public void setTbLichSuBaoTris(Set<TbLichSuBaoTri> tbLichSuBaoTris) {
		this.tbLichSuBaoTris = tbLichSuBaoTris;
	}

}
